### ISSUE TITLE
vs Symmetric Encryption

### ISSUE THREAD

**Issue by ghost** [derhuerst/html-vault#6]
What is special having this as an HTML file versus simply using symmetric encryption?

**Comment by derhuerst** [comment]
The special feature is that the HTML can decrypt the message by itself: Any person with a reasonably modern browser (and any reasonably backwards-compatible browser in the future) will be able to decrypt and view the message. No external tools are needed, and therefore no version incompatibilities, UX problems, etc.

Please re-open if your question has not been answered.
